spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: findfriends
      uri: mongodb://root:password@localhost:27017/findfriends?authSource=admin

  application:
    name: findfriends

  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.tutorial.idarabi.findfriends: INFO

app:
  jwtSecret: mySecretKey
  jwtExpirationInMs: 604800000